name: Deploy to Firebase on merge
'on':
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '24'
      - uses: FirebaseExtended/action-hosting-deploy@master
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: dataflow-monitor-mockup
          entryPoint: .
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
